/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.trainer;

import Business.Logic.CusDic;
import Business.Logic.TraDic;
import Business.Models.CourseRecord;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import userinterface.MainJFrame;

/**
 *
 * @author Administrator
 */
public class ViewCourseRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCourseRecordJPanel
     */
    public ViewCourseRecordJPanel() {
        initComponents();
        LoadRecord();
    }
    public void LoadRecord(){
        List<CourseRecord> listCourseRecord = TraDic.GetCourseRecord();
        String[] cols = new String[]{"Course Name","Date","Time","Customer","Sign Time"};
        String[][] rows= new String[listCourseRecord.size()][5];
        for (int i = 0; i < listCourseRecord.size(); i++) {
            rows[i][0] = listCourseRecord.get(i).CourseName;
            rows[i][1] = listCourseRecord.get(i).CourseDate;
            rows[i][2] = listCourseRecord.get(i).CourseTime;
            rows[i][3] = listCourseRecord.get(i).realname;
            rows[i][4] = listCourseRecord.get(i).CheckTime;
            
        }
        DefaultTableModel tableModel = (DefaultTableModel)this.tableCourseRecord.getModel();
        tableModel.setDataVector(rows, cols);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourseRecord = new javax.swing.JTable();

        tableCourseRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCourseRecord);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCourseRecord;
    // End of variables declaration//GEN-END:variables
}
