/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.user;

import Business.Logic.OrgDic;
import Business.Logic.UserDic;
import Business.Models.Org;
import Business.Models.Role;
import Business.Models.User;
import Common.MessageCode;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import userinterface.MainJFrame;

/**
 *
 * @author Administrator
 */
public class ManageUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserJPanel
     */
    public ManageUserJPanel() {
        initComponents();
        LoadData();
         if(MainJFrame.user.type.equals("10")){
             List<Org> listOrg = OrgDic.QueryOrg("1");
            for (int i = 0; i < listOrg.size(); i++) {
                this.comboNetWork.addItem(listOrg.get(i));
            }
         }
         else if(MainJFrame.user.type.equals("11")==false&&MainJFrame.user.type.equals("5")==false){
             this.comboNetWork.setEnabled(false);
             this.comboCompany.setEnabled(false);
             Org org= OrgDic.GetOrg(MainJFrame.user.OrgID);
             if(org!=null){
                 List<Org> listOrg = OrgDic.QueryOrg(org.ParentID);
                 for (int i = 0; i < listOrg.size(); i++) {
                    this.comboOrg.addItem(listOrg.get(i));
                }
             }
         }
         else{
             this.comboNetWork.setEnabled(false);
             this.comboCompany.setEnabled(false);
             this.comboOrg.setEnabled(false);
         }
        
        if(MainJFrame.user.type.equals("10")){//超级管理员能创建11、12、13、14类型用户
            this.comboRole.addItem(new Role("11","CustomAdmin"));
            this.comboRole.addItem(new Role("12","GymAdmin"));
            this.comboRole.addItem(new Role("13","RestaurantAdmin"));
            this.comboRole.addItem(new Role("14","PhysicalAdmin"));
        }
        else if(MainJFrame.user.type.equals("11")){
            this.comboRole.addItem(new Role("1","VipCustom"));
            this.comboRole.addItem(new Role("2","Vip2Custom"));
        }
        else if(MainJFrame.user.type.equals("5")){
            this.comboRole.addItem(new Role("1","VipCustom"));
            this.comboRole.addItem(new Role("2","Vip2Custom"));
        }
        else if(MainJFrame.user.type.equals("12")){
            this.comboRole.addItem(new Role("3","Private Trainer"));
            this.comboRole.addItem(new Role("4","Vip Trainer"));
            this.comboRole.addItem(new Role("5","Reception"));
            this.comboRole.addItem(new Role("6","Engineer"));            
        }
        else if(MainJFrame.user.type.equals("13")){
            this.comboRole.addItem(new Role("7","Cooker")); 
            this.comboRole.addItem(new Role("8","Dietician"));            
        }
        else if(MainJFrame.user.type.equals("14")){
            this.comboRole.addItem(new Role("9","Doctor")); 
        }
    }
    public void LoadData(){
        List<User> list = new ArrayList();
        if(MainJFrame.user.type.equals("10")){
            list = UserDic.QueryUseyByTypes(new String[]{"11","12","13","14"});
        }
        else if(MainJFrame.user.type.equals("5")||MainJFrame.user.type.equals("11")){
            list = UserDic.QueryUseyByTypes(new String[]{"1","2"});
        }
        else if(MainJFrame.user.type.equals("12")){
            list = UserDic.QueryUseyByTypes(new String[]{"3","4","5","6"});
        }
        else if(MainJFrame.user.type.equals("13")){
            list = UserDic.QueryUseyByTypes(new String[]{"7","8"});
        }
        else if(MainJFrame.user.type.equals("14")){
            list = UserDic.QueryUseyByTypes(new String[]{"9"});
        }
        DefaultTableModel tableModel = (DefaultTableModel)this.tableUser.getModel();
        String[] cols = new String[]{"username","realname","Role","Org"};
        String[][] rows= new String[list.size()][4];
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).username;
            rows[i][1] = list.get(i).realname;
            rows[i][2] = Role.Translate(list.get(i).type);
            rows[i][3] =OrgDic.GetOrgPath(list.get(i).OrgID) ;
        }
        tableModel.setDataVector(rows, cols);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPsw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRealName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<Role>();
        btnSave = new javax.swing.JButton();
        labInfo = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboNetWork = new javax.swing.JComboBox<Org>();
        comboCompany = new javax.swing.JComboBox<Org>();
        comboOrg = new javax.swing.JComboBox<Org>();

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableUser);

        jLabel1.setText("User Name:");

        jLabel2.setText("Password:");

        jLabel3.setText("RealName:");

        jLabel4.setText("Role:");

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<Role>());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setText("Delete User");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel5.setText("Org");

        comboNetWork.setModel(new javax.swing.DefaultComboBoxModel<Org>());
        comboNetWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetWorkActionPerformed(evt);
            }
        });

        comboCompany.setModel(new javax.swing.DefaultComboBoxModel<Org>());
        comboCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCompanyActionPerformed(evt);
            }
        });

        comboOrg.setModel(new javax.swing.DefaultComboBoxModel<Org>());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRealName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRole, 0, 113, Short.MAX_VALUE)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNetWork, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtRealName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboNetWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(labInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String username = this.txtUserName.getText();
        String psw = this.txtPsw.getText();
        String realname = this.txtRealName.getText();
        Role r = (Role)this.comboRole.getSelectedItem();
        String OrgID = MainJFrame.user.OrgID;
        if(username.isEmpty()||psw.isEmpty()||realname.isEmpty()){
            this.labInfo.setText("User Info Empty");
            return;
        }
        if(MainJFrame.user.type.equals("11")==false&&MainJFrame.user.type.equals("5")==false){
            if(this.comboOrg.getSelectedIndex()==-1){
                this.labInfo.setText("Org required");
               return;
            }
            Org org = (Org)this.comboOrg.getSelectedItem();
            OrgID = org.ID;
        }
        int res = UserDic.AddUser(username, psw, realname, r.Type,OrgID);
        if(res!=MessageCode.SUCCESS){
            this.labInfo.setText("User Name EXSIST");
            return;
        }
        LoadData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int n = this.tableUser.getSelectedRow();
        if(n>=0){
            String username = this.tableUser.getValueAt(n,0).toString();
            int res = UserDic.DelUser(username);
            if(res!=MessageCode.SUCCESS){
                this.labInfo.setText("Delete Failed");
                return;
            }
            LoadData();
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void comboNetWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetWorkActionPerformed
        Org org = (Org)this.comboNetWork.getSelectedItem();
        System.out.println(org);
        List<Org> listOrg = OrgDic.QueryOrg(org.ID);
        this.comboCompany.removeAllItems();
        for (int i = 0; i < listOrg.size(); i++) {
            this.comboCompany.addItem(listOrg.get(i));
        }
    }//GEN-LAST:event_comboNetWorkActionPerformed

    private void comboCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCompanyActionPerformed
           Org org = (Org)this.comboCompany.getSelectedItem();
            List<Org> listOrg = OrgDic.QueryOrg(org.ID);
        this.comboOrg.removeAllItems();
        for (int i = 0; i < listOrg.size(); i++) {
            this.comboOrg.addItem(listOrg.get(i));
        }
    }//GEN-LAST:event_comboCompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Org> comboCompany;
    private javax.swing.JComboBox<Org> comboNetWork;
    private javax.swing.JComboBox<Org> comboOrg;
    private javax.swing.JComboBox<Role> comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labInfo;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtPsw;
    private javax.swing.JTextField txtRealName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
