/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.user;

import Business.Logic.OrgDic;
import Business.Models.Org;
import Business.Models.SysMenu;
import Common.DB;
import java.util.List;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import static userinterface.MainJFrame.user;

/**
 *
 * @author Administrator
 */
public class OrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganizationJPanel
     */
    private Org selected_Org=null;
    public OrganizationJPanel() {
        initComponents();
        btnSave.setEnabled(false);
        InitTree();
        LoadTree();
        
    }
    public void LoadTree(){
        DB db = DB.getDB();
        List<Org> list = OrgDic.QueryOrg("0");
        DefaultMutableTreeNode nodeTop = new DefaultMutableTreeNode(list.get(0));
        LoadSub(nodeTop);
        TreeModel treeModel = new DefaultTreeModel(nodeTop);
        this.treeOrg.setModel(treeModel);
       
    }
    public void LoadSub(DefaultMutableTreeNode nodeP){
        Org o = (Org)nodeP.getUserObject();
        List<Org> list = OrgDic.QueryOrg(o.ID);
        for (int i = 0; i < list.size(); i++) {
            DefaultMutableTreeNode subNode = new DefaultMutableTreeNode(list.get(i));
            nodeP.add(subNode);
            LoadSub(subNode);
            
        }
    }
    public void InitTree(){
         this.treeOrg.addTreeSelectionListener(new TreeSelectionListener() {
 
            @Override
            public void valueChanged(TreeSelectionEvent e) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeOrg
                        .getLastSelectedPathComponent();
                if (node == null)
                 {
                     btnSave.setEnabled(false);
                     return;
                 }
                btnSave.setEnabled(true);
                Org org = (Org)node.getUserObject();
                selected_Org = org;
                if (node.isLeaf()) {
                   btnDel.setEnabled(true);
                }
                 else{
                    btnDel.setEnabled(false);
                }
 
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeOrg = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        jScrollPane1.setViewportView(treeOrg);

        jLabel1.setText("Org Name");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setText("Delete Selected");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave))
                    .addComponent(btnDel))
                .addGap(0, 239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = this.txtOrgName.getText();
        if(name.isEmpty()){
            return;
        }
        boolean res= OrgDic.AddOrg(DB.UIID(),name , this.selected_Org.ID);
        if(res){
            this.LoadTree();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        boolean res= OrgDic.DelOrg(this.selected_Org.ID);
        if(res){
            this.LoadTree();
        }
    }//GEN-LAST:event_btnDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treeOrg;
    private javax.swing.JTextField txtOrgName;
    // End of variables declaration//GEN-END:variables
}
