/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.reception;

import Business.Logic.RecDic;
import Business.Logic.TraDic;
import Business.Models.SignInStc;
import Business.Models.VipCustomer;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import userinterface.MainJFrame;

/**
 *
 * @author Administrator
 */
public class SignInStcJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignInStcJPanel
     */
    public SignInStcJPanel() {
        initComponents();
        LoadTrainerCourse();
        LoadCustomerCourse();
    }
    public void LoadTrainerCourse(){
        List<SignInStc> list = RecDic.StcTrainerCourse();
        String[] cols = new String[]{"Trainer Name","Course Count"};
        String[][] rows= new String[list.size()][2];
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).realname;
            rows[i][1] = String.format("%d", list.get(i).Count);   
        }
        DefaultTableModel tableModel = (DefaultTableModel)this.tableCourse.getModel();
        tableModel.setDataVector(rows, cols);
    }
    public void LoadCustomerCourse(){
        List<SignInStc> list = RecDic.StcCustomerCourse();
        String[] cols = new String[]{"Customer Name","Course Count"};
        String[][] rows= new String[list.size()][2];
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).realname;
            rows[i][1] = String.format("%d", list.get(i).Count);   
        }
        DefaultTableModel tableModel = (DefaultTableModel)this.tableCustomer.getModel();
        tableModel.setDataVector(rows, cols);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();

        jLabel1.setText("Trainer Course");

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCourse);

        jLabel2.setText("Customer Course");

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCourse;
    private javax.swing.JTable tableCustomer;
    // End of variables declaration//GEN-END:variables
}
